### ISSUE TITLE
setup.py got deleted

### ISSUE THREAD

**Issue by beasteers** [beetbox/confuse#103]
It looks like it happened when merging this PR: https://github.com/beetbox/confuse/commit/ba47c6ac7fd05458f3be5a1fe8b3e67e3f5fb66e

This is a problem because now you can't do:

```
pip install git+https://github.com/beetbox/confuse.git
```

**Comment by beasteers** [comment]
At first, I thought it was just deleted accidentally, but taking a closer look it looks like you're switching to `flit` as an alternative to `setuptools`.

I got a message from a coworker that she was getting this error (` FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-b18rxqtq/confuse/setup.py'`) on her raspberry pi and I confirmed it on mine as well. It appears to be a debian issue, because pip installing from git does work on my mac.

What motivated the switch to `flit`?

**Comment by sampsyo** [comment]
Hi! The main reason is a maintenance headache—Flit solves several problems that the old `setup.py`/`setup.cfg`/`MANIFEST.in` miasma introduce. The proximate cause was #101, where apparently we forgot to include a file in the distribution—the nice thing about Flit here is that just makes that problem go away entirely by including everything that's checked into git by default.

That is an unfortunate consequence, however. Fortunately, I think it's "just" a pip version problem: recent versions of pip should be able to handle `pyproject.toml` installations from git in the same way that they handle `setup.py` projects. Perhaps the coworker's Raspberry Pi/Debian issues can be resolved with a `pip install --user -U pip` upgrade or similar?

**Comment by beasteers** [comment]
Ah I see. I don't usually go past `setup.py` with a simple `setuptools.setup()` block for packages so I wasn't sure lol - I'll have to read about `pyproject.toml` files.

Yeah upgrading pip did seem to do the trick! I'll have to pass this on to my coworker to test, but I guess we can close this.

Thanks for the explanation/help!

**Comment by sampsyo** [comment]
`pyproject.toml` is very new!! In the grand scheme of things, at least. And as someone who has written one too many `setup.py`s, I'm extremely excited to move out of the dark ages and into the light. :smiley:
