### ISSUE TITLE
Hot reloading

### ISSUE THREAD

**Issue by pbrissaud** [beetbox/confuse#138]
Hi,

I was wondering if this cool library can perform hot reloading to update config in live if the file changed. 

Eg:

`main.py`
```python
import confuse
import sys
import time

if __name__ == "__main__":
  config = confuse.Configuration('app', __name__)
  print(config)
  time.sleep(20)
  print(config)
  sys.exit(0)
```

`~/.config/app/config.yaml`
```yaml
foo: bar
```

I launch the program, then I modify the `config.yaml` file to 
```yaml
foo: bar
test: hello world
```

Program output:
```bash
$ python3 main.py
{'foo': 'bar'}  # I change the config.yaml file after this output
{'foo': 'bar'}  # Sould be {'foo': 'bar', 'test': 'hello world'}
# Relaunching program to be sure 
% python3 main.py
{'foo': 'bar', 'test': 'hello world'}
{'foo': 'bar', 'test': 'hello world'}
```

Thanks

**Comment by sampsyo** [comment]
Yo! We don't have anything that automatically watches for on-disk file changes (that's a little complicated to do in a cross-platform way), but you can consider manually reloading sources when stuff might have changed. Something like this (not that I've tested it):

```py
for source in config.sources:
    if isinstance(source, confuse.sources.YamlSource):
        source.load()
```

**Comment by pbrissaud** [comment]
Thanks for your quick answer, I will look to your solution !

**Comment by pbrissaud** [comment]
Your solution works like a charm, a big thanks ! Any plans to integrate this as a builtin method in the library (eg: `config.reload()`) ?

**Comment by sampsyo** [comment]
I certainly have no objection to adding such a thing! Would you be interested in opening a pull request?

**Comment by pbrissaud** [comment]
Yeah of course !
