### ISSUE TITLE
Set Python to >=3.6 Instead of >=3.6,<4.0

### ISSUE THREAD

**Issue by rbebb** [beetbox/confuse#153]
Since `confuse` has its `python` version set to `>=3.6,<4.0`, all downstream projects that use `poetry` to manage dependencies have to set their `python` versions to `^3.6`/`>=3.6,<4.0`. While this doesn't necessarily cause any issues, it would be nice to be able to leave the version range open by using `>=3.6`.

**Comment by sampsyo** [comment]
Sure, sounds good. The `<4.0` thing was kinda a standard recommendation back in the Python 2/3 tradition, but it has clearly fallen out of favor. Would you mind whipping up a quick PR?

**Comment by rbebb** [comment]
@sampsyo Sure! It says I don't have permission to push to your repo though

**Comment by sampsyo** [comment]
That should be fine… you should be able to create a "fork" of this repo under your name, push commits there, and use that for a PR.
