### ISSUE TITLE
Dumping a configuration to file does not work

### ISSUE THREAD

**Issue by luusl** [beetbox/confuse#47]
It seems that dumping the config to a file has been removed with [this commit](https://github.com/sampsyo/confuse/commit/415ccdb22c320a34dd799810d6f0d571ddcf03da). Please update documentation or re-introduce this option.

**Comment by jackwilsdon** [comment]
It looks like dumping is still supported, but you can no longer specify a filename.

**Comment by luusl** [comment]
The method returns a string which can be written, but the method itself has no code to be able to write to a file.

**Comment by jackwilsdon** [comment]
Hmm yeah you're right, I apologise. Looks like the documentation needs updating.

**Comment by sampsyo** [comment]
Indeed; thanks for pointing that out, @luusl! Any chance we could get your help to open a pull request that deletes the relevant sentence from the docs?
https://github.com/sampsyo/confuse/blob/master/docs/index.rst#yaml-tweaks
