### ISSUE TITLE
OS Environment variables

### ISSUE THREAD

**Issue by moraisaugusto** [beetbox/confuse#57]
Is there possible to import OS environment variable on yaml config file?

**Comment by sampsyo** [comment]
Can you clarify what you mean? What would “importing” an environment variable look like?

**Comment by moraisaugusto** [comment]
Inside the yaml config file, Is it possible to add an OS variable and access it thought the confuse? Something like this:

```bash
$ export DB_USER="myuser"
$ export DB_PASS="mypass"
```

config.yaml
```yml
database:
    user: ${DB_USER}
    pass: ${DB_PASS}

**Comment by sampsyo** [comment]
Aha—no, that's not currently possible. The syntax you're proposing there is similar to #56, which is not really part of the goals for this library.

Of course, it's possible for your program to provide environment variables as _defaults_ for configured overrides! For example, you might do something like:

```py
config.add({
    'database': {
        'user': os.environ['DB_USER'],
        'pass': os.environ['DB_PASS'],
    }
})

**Comment by elebow** [comment]
I believe this is now provided through `.as_str_expanded()`, which was added in https://github.com/beetbox/confuse/pull/59.
