### ISSUE TITLE
Question about locations of config files.

### ISSUE THREAD

**Issue by antonedvard** [beetbox/confuse#63]
Im currently setting up a new project and i am trying to use confuse to parse .yaml config files.

I am trying to make my project modular in somewhat way and im having massive issues referring to the config file.

I want the user/app to be able to check if there is an `config.yaml` file inside the root folder of the project, if that does not exist then i want confuse to use `default_config.yaml` within the modules folder.

Currently writing on a mac osx but i guess this should be able to work accross all types of OS's but when i print config.user_config.path() then i get `/Users/$USER/Library/Application Support/ili/config.yaml`

I have searched EVERYWHERE for a place to change the root folder or where the confuse module fetches the `config.yaml` file from but it seems it is hardcoded within `..._DIR` variables set at the top of the `confuse.py` file, is there any method or "config" to change that, it is not looking in env-variables cus i have tried to change that too and it doesn't work...

Best regards!

**Comment by jackwilsdon** [comment]
I haven't tested this, but I don't see why you couldn't extend `Configuration` or `LazyConfig` and override `config_dir` like so:

```Python
class MyConfig(confuse.Configuration):
    def config_dir(self):
        return "/tmp"
```

**Comment by jlumbroso** [comment]
So perfect, that's exactly the question I had. Thanks for that answer. Here is how I added local working directory as a top search path:

```python
import os as _os
import confuse as _confuse

class LocalDirConfig(_confuse.LazyConfig):

    def config_dir(self):

        local_config = _os.path.join(_os.getcwd(), _confuse.CONFIG_FILENAME)
        if _os.path.exists(local_config):
            return _os.getcwd()

        return super(LocalDirConfig, self).__init__()
```

**Comment by antonedvard** [comment]
Ofcourse i can do that, haha! Thanks for the quick feedback! 😄

**Comment by sampsyo** [comment]
Awesome, and nice work, @jackwilsdon. :smiley:
