### ISSUE TITLE
debug usage?

### ISSUE THREAD

**Issue by melophat** [beetbox/confuse#64]
Forgive the possibly stupid question here..

I'm adding Confuse to a project that I'm working on to handle the yaml config files, and looking through the docs, I see a reference to debug levels in the example file, but I'm not quite sure if debug level functionality is something that is built in to Confuse, or if I need to implement debugging myself and can utilize Confuse to get the levels from the command line/yaml file.

**Comment by sampsyo** [comment]
The latter!

**Comment by melophat** [comment]
got it.  Thanks for the quick response and keep up the great work.. this package has made my life in python with YAML much easier. Thanks!
