### ISSUE TITLE
Add support for instantiating python objects from yaml file

### ISSUE THREAD

**Issue by jlquinn** [beetbox/confuse#67]
We make use of the PyYaml library ability to instantiate a python object from a yaml declaration.  In order to do so, I patch Loader to derive from yaml.Loader instead of yaml.SafeLoader.  I get that you don't necessarily want that to be the default.  But it would be awesome to have the ability to be part of the unpatched library.

**Comment by sampsyo** [comment]
Sounds interesting! Another way to get a Python object from the configuration, of course, would be to define your own `Template` for translating from the underlying data to your application's data objects.

But maybe that won't work… anyway, sure, I'd be happy to merge a PR that adds a hook for specifying the `Loader` class if it's not too complex.

**Comment by nka11** [comment]
Hope this PR is not too complicated, but it fixes for sure this issue.

I'm able to use default Loader or any Loader from underlying pyYaml package.

**Comment by sampsyo** [comment]
Fixed in #92.
