### ISSUE TITLE
Publish v1.1.0 to PyPI?

### ISSUE THREAD

**Issue by iamkroot** [beetbox/confuse#71]
It seems that you've finalized the changelog for v1.1.0, as per the [latest](https://github.com/beetbox/confuse/commit/81764c357302beb627ca3e7ede7f239c87a2069d) commit. It'd be really helpful if you publish the update to PyPI, since I'd like to make use of the Path template :)

**Comment by sampsyo** [comment]
Sure, happy to do a release. For what it's worth, I generally like to keep changelogs in a "rolling" style, updating them continuously whenever there's an update rather than doing it all at once when it's time to release. So hopefully we can keep that up from here on out.

**Comment by sampsyo** [comment]
Released! https://pypi.org/project/confuse/1.1.0/

**Comment by iamkroot** [comment]
Sorry for the misunderstanding then.  Thanks for the release! 😁
