### ISSUE TITLE
Support default values for Filename and Path objects

### ISSUE THREAD

**Issue by palto42** [beetbox/confuse#76]
It seems that the Filename and Path classes don't support the use of default values as it is possible for example with confuse.String() or confuse.Integer().

I tried to define defaults in the template dict like:

```
template = {
    "TEMP_PATH": confuse.Filename(default="/tmp"),
}
```

But if I check the configuration file with `config.get(template)` , an error is raised `confuse.NotFoundError: TEMP_PATH not found` (if it's not defined in the config.yaml).

Instead I expected that TEMP_PATH will be set to "/tmp".

Is the "default" option not implemented for `Filename` or do I use it incorrectly?

**Comment by sampsyo** [comment]
Thanks for pointing this out! As it happens, @beasteers filed a similar issue (#77) on the same day that points out what has gone wrong here. It's a bug—we intended to be able to support defaults for filename templates but have neglected to actually implement it. :flushed:

**Comment by palto42** [comment]
@sampsyo thanks for your quick response!

I did some "quick fix", but not sure if this is the best approach:

    def value(self, view, template=None):
        if view.exists():
            path, source = view.first()
        elif self.default is not REQUIRED:
            path = self.default
            # if no absolute path, it will be relative to the app's directory.
            source = ConfigSource("", filename="")
        else:
            raise NotFoundError(u"{0} not found".format(view.name))

Especially I'm not sure about the setting of `source`, but for me it worked.

**Comment by sampsyo** [comment]
Cool! See also #79 for @beasteers's full PR.
