### ISSUE TITLE
[Doc improvement] Add examples

### ISSUE THREAD

**Issue by mathieu-mp** [beetbox/confuse#84]
Hi,

I'd like to suggest to add some basic and advanced examples to the docs.
I had to dig into the issues to find how to add a secondary source config file via set_file, and its precedence order. This improvement would save some time to newcomers.

It might simply look like:
```python
import confuse

# Instanciates config. Confuse searches for a config_default.yaml
config = confuse.Configuration('MyGreatApp')
# Add config items from specific file
config.set_file('subdirectory/default_config.yaml')
# Add config items from a second file. If some item were already defined, they will be overwritten (new file precedes the previous ones)
config.set_file('subdirectory/local_config.yaml')

# Fetch the value
foo_bar_value = config['foo']['bar'].get()
# Fetch the value of specific type, exception will be raised if type doesn't match
foo_bar_int_value = config['foo']['bar'].get(int)
```

Good job with this great tool !

**Comment by sampsyo** [comment]
Sounds cool! If you are interested, any chance you could get use started with a pull request? Taking your current example here and putting it into context in the docs would be a great place to start!

**Comment by mvadu** [comment]
Shouldn't this issue be closed since the doc now provide this example?

**Comment by sampsyo** [comment]
Sure; sounds good! Thanks for the reminder.
