### ISSUE TITLE
None as Template should use None as default

### ISSUE THREAD

**Issue by beasteers** [beetbox/confuse#93]
When I do this for a key that doesn't exist in `config_default.yaml`, I would expect the key to contain `None` by default.
```python
config['something'].get({
    'key': None
})
```

But instead, I get:
```
confuse.NotFoundError: something.key not found
```

This is because of this line in `as_template`:
https://github.com/beetbox/confuse/blob/b82d3faacb972b8964487a648805c3d0e06c0212/confuse.py#L1718-L1719

What I would propose:
```python
# throws NotFoundError - '...' is often used to denote a missing value
config['something'].get({
    'key': ...
})

# returns None
config['something'].get({
    'key': None
})
```

**Comment by sampsyo** [comment]
Hmm, that does seem somewhat surprising. I'm honestly not entirely sure why it works that way currently… maybe some other template relies on `None` being the same as a missing value elsewhere? It's worth trying to change it and giving it a shot to see if anything breaks.

I'm a little wary of using the `Ellipsis` object, whose main purpose is in slicing syntax… I'm not sure the current behavior is all that useful, but folks can always accomplish it with `confuse.Template()`.

**Comment by beasteers** [comment]
This change shouldn't affect any other templates, it's purely how `None` is translated from shorthand to a template object. The unspecified value in `confuse.Template(...)` is `REQUIRED` so an alternative is to use `confuse.REQUIRED` for required fields.

Ya I know that you can use `confuse.Template(None)`, but it always feels like unexpected behavior to specify `None` and have it error out. I'm just so used to setting function defaults to None to mean that its value is optional.

I agree that the ellipsis may not be semantically perfect. It can a useful substitute for `None` in situations where `None` is a valid input value and you need to signify a true missing value. Though in many cases a sentinel value (e.g. `REQUIRED = object()`) works, so we can just go with that. (The ellipsis was just a shot at brevity.)

**Comment by sampsyo** [comment]
Cool, I'm definitely down with using `confuse.REQUIRED`! And indeed, the `None` behavior currently is quite surprising, given that most other simple values just turn into templates where that value is the default.

(TBH I'm having trouble imagining a situation where someone would want to use the current behavior… wouldn't you always prefer to just leave the key out of your template? But anyway, the `REQUIRED` thing seems like it certainly can't hurt.)

**Comment by beasteers** [comment]
Personally I feel more comfortable having my scripts be able to run if it got separated from the `config_default.yaml` so I try to always set working defaults independent of external config. But I guess someone may want to throw an error if someone didn't specify a value in their config that they needed to so I guess there could be some cases? 🤷‍♀️

**Comment by beasteers** [comment]
While we're (somewhat) on the topic of natural feeling default values, I find that I end up with this pattern quite often and it can be tedious. 

```python
cfgml = config['audio']['ml'].get({
    'inp_sr': 48000,
    'channels': 1,
    'model_path': None,
    'classifier_path': None,
    'enabled': True,
    'hop_size': 0.1,
    'sr': 8000,
    'duration': 1,
    'n_fft': 1024,
    'n_mels': 64,
    'mel_hop_len': 160,
    'fmax': None,
    'classes': None,
    'batch_size': 1,
})

class Model:
    def __init__(self, model_path=cfgml.model_path, cls_path=cfgml.classifier_path,
                 hop_size=cfgml.hop_size,
                 classes=cfgml.classes,
                 channels=cfgml.channels,
                 fs=cfgml.inp_sr,
                 fmt=np.int16,
                 target_sr=cfgml.sr,
                 n_fft=cfgml.n_fft,
                 n_mels=cfgml.n_mels,
                 mel_hop_len=cfgml.mel_hop_len,
                 fmax=cfgml.fmax,
                 batch_size=cfgml.batch_size):
        pass

```

So I was thinking that maybe an elegant solution is to have the function signature+defaults double as the template.

```python
class Model:
    @config.bind('audio.ml')
    def __init__(self, model_path, classifier_path=None,
                 hop_size=confuse.Number(0.1),
                 classes=confuse.REQUIRED,
                 channels=1,
                 sr=8000,
                 fmt=np.int16,
                 n_fft=1024,
                 n_mels=64,
                 mel_hop_len=160,
                 fmax=None,
                 batch_size=1):
        pass
```

**Comment by sampsyo** [comment]
Oh wow, that's pretty nifty! Would this also pull the values out of the configuration for you so you could just refer to parameters like `batch_size` directly instead of using `config['batch_size'].get()`?

**Comment by beasteers** [comment]
Yep! Here's some pseudo-code of basically how it could work. If we didn't have to deal with positional arguments, it would be pretty much this simple, but we'll still need to work around positional arguments and positional only arguments, and figure out what we want to do with any `*a, **kw` found in the signature.

```python
def bind(source='', sep='.'):
    def outer(func):
        # get config from function signature
        tmpls = get_function_defaults(func) # using inspect or whatev
        cfgkw = config[source.split(sep)].get(**tmpls)

        def inner(*a, **kw):
            # need to handle overrides w/ positional arguments
            return func(*a, **dict(cfgkw, **kw))
        return inner
    return outer
```

**Comment by sampsyo** [comment]
Nice; that looks really cool! Especially for smallish programs/components that want to read all of the config values up front. I really like that it should be possible to do this for any given view, i.e., for just a part of a larger config. :+1:

**Comment by beasteers** [comment]
Yeah I often find myself wishing I could just take a function's default arguments and outsource+modify them in a config so this would make it super easy.

Two things that would also be useful for this:
 - being able to pass the config view scope at call time (if there is a dynamic config schema (e.g. list of dicts))
    - maybe you pass the config view as an argument (e.g. `wrapped_func(_cfg=config['myview'][3])` or something
 - multiple fallback config scopes - for example be able to access a root config variable like `data_dir` while having the rest come from the subview
    - I'm less sure about this, but maybe the way to do it would be to make subviews usable as a config source.

**Comment by beasteers** [comment]
Back to the original issue, should we make it so that for any unknown value `as_template` will convert to `confuse.Template(something)` instead of throwing a `ValueError`?

Basically conversion could look like this:
```python
WHATEVER = object()
{
    'a': None, # confuse.Template(None)
    'b': confuse.REQUIRED, # confuse.Template()
    'c': confuse.UNSET, # confuse.Template(confuse.UNSET)
    'd': WHATEVER, # confuse.Template(WHATEVER)
}
```
